---
login: "login"
password: "password"
profiles:
  - cristiano
  - selenagomez
  - madonna
logging:
  version: 1
  formatters:
    simple:
      format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    user:
      format: "%(login)s - %(asctime)s - %(levelname)s - %(message)s"
  handlers:
    telegram:
      level: WARNING
      class: telegram_handler.TelegramHandler
      token: TELEGRAM_BOT_TOKEN
      chat_id: TELEGRAM_CHAT_ID
      proxies:
        http: HTTP_PROXY_URL
        https: HTTPS_PROXY_URL
    console:
      class: logging.StreamHandler
      formatter: simple
      stream: "ext://sys.stdout"
  loggers:
    instabot:
      level: INFO
      handlers:
        - telegram
        - console